name: Tests

on:
  pull_request:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  schedule:
    - cron: '42 0 1 * *' # on 1st day of every month at 00:42

jobs:
  test:
    # Skip running tests for local pull requests (use push event instead), run only for foreign ones
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.owner.login != github.event.pull_request.base.repo.owner.login
    name: 'Ruby ${{ matrix.ruby }} × AR ${{ matrix.activerecord }} × Yabeda ${{ matrix.yabeda }}'
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.optional || false }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: '2.7'
            activerecord: '6.1'
            yabeda: '0.11'
          - ruby: '3.0'
            activerecord: '7.0'
            yabeda: '0.11'
          - ruby: '3.1'
            activerecord: '7.1'
            yabeda: '0.12'
          - ruby: '3.2'
            activerecord: '7.2'
            yabeda: '0.13'
          - ruby: '3.3'
            activerecord: '8.0'
            yabeda: '0.14'
          - ruby: '3.4'
            activerecord: '8.0'
            yabeda: '0.14'
          - ruby: 'head'
            activerecord: 'HEAD'
            yabeda: 'HEAD'
            optional: true
    env:
      YABEDA_VERSION: ${{ matrix.yabeda }}
      ACTIVERECORD_VERSION: ${{ matrix.activerecord }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run RSpec
        run: bundle exec rspec
